import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { StoreProvider } from "@/store/StoreProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "D-SERVE",
  description: "Generated by D-SERVE",
  icons: {
    icon: "/img/logo2.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-nunito ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <div className=" min-w-[277px] min-h-screen">
            <NextTopLoader color="#a16207" showSpinner={false} height={3} />
            {children}
            <ToastContainer position="top-center" autoClose={4000} />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
